"""Create core project metadata tables

Revision ID: 776fd7c658af
Revises: 
Create Date: 2026-07-29 20:15:23.289824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776fd7c658af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('task_type', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("task_type IN ('tabular_classification', 'tabular_regression', 'object_detection')", name='ck_projects_task_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_projects_created_at', ['created_at'], unique=False)

    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dataset_type', sa.String(length=40), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index('ix_datasets_project_id', ['project_id'], unique=False)

    op.create_table('dataset_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('labelled_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'version_number', name='uq_dataset_versions_number')
    )
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.create_index('ix_dataset_versions_dataset_id', ['dataset_id'], unique=False)

    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=1024), nullable=False),
    sa.Column('class_name', sa.String(length=255), nullable=False),
    sa.Column('x_min', sa.Float(), nullable=False),
    sa.Column('y_min', sa.Float(), nullable=False),
    sa.Column('x_max', sa.Float(), nullable=False),
    sa.Column('y_max', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source IN ('human', 'model', 'human_corrected', 'imported')", name='ck_annotations_source'),
    sa.CheckConstraint('x_max > x_min AND y_max > y_min', name='ck_annotations_positive_box'),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index('ix_annotations_dataset_version_id', ['dataset_version_id'], unique=False)

    op.create_table('training_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('configuration_json', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed', 'cancelled')", name='ck_training_jobs_status'),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='ck_training_jobs_progress'),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_training_jobs_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_training_jobs_status', ['status'], unique=False)

    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('training_job_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('model_path', sa.String(length=1024), nullable=False),
    sa.Column('export_path', sa.String(length=1024), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('configuration_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_job_id'], ['training_jobs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version_number', name='uq_model_versions_project_number')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index('ix_model_versions_project_id', ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_model_versions_project_id')

    op.drop_table('model_versions')
    with op.batch_alter_table('training_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_training_jobs_status')
        batch_op.drop_index('ix_training_jobs_project_id')

    op.drop_table('training_jobs')
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index('ix_annotations_dataset_version_id')

    op.drop_table('annotations')
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_dataset_versions_dataset_id')

    op.drop_table('dataset_versions')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index('ix_datasets_project_id')

    op.drop_table('datasets')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_created_at')

    op.drop_table('projects')
    # ### end Alembic commands ###
