"""Add active model version state

Revision ID: b136aa119886
Revises: 776fd7c658af
Create Date: 2026-07-29 21:03:23.987014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b136aa119886'
down_revision = '776fd7c658af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
